version: '2.1'
services:
  # Base services
  cache:
    extends:
      file: docker-services.yml
      service: cache
  db:
    extends:
      file: docker-services.yml
      service: db
  mq:
    extends:
      file: docker-services.yml
      service: mq
  os:
    extends:
      file: docker-services.yml
      service: os
    volumes:
    - esdata:/usr/share/elasticsearch/data
volumes:
  esdata:
    driver: local
